[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = skip
warn_redundant_casts = False
warn_unused_ignores = False


[mypy-google.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-vertexai.*]
ignore_missing_imports = True